# action.yml
name: 'Binoc Bot'
description: 'Binoc is a GitHub Actions Workflow that can update package build instructions in GitHub Repositories.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/autamus/binoc:latest'
