# action.yml
name: 'Binoc Bot'
description: 'Binoc is a GitHub Actions Workflow that can update package build instructions in GitHub Repositories.'
inputs:
  repo-path:
    description: 'Location of the Package Build Instructions'
    required: false
    default: '/'
  git-name:
    description: 'Name used within Git for the commits'
    required: false
    default: 'Binoc'
  git-email:
    description: 'Email used within Git for the commits'
    required: false
    default: 'github-action@users.noreply.github.com'
  git-username:
    description: 'Username used within Git for pushing commits'
    required: false
    default: 'github.actor'
  git-token:
    description: 'Token used for authenticating with the upstream repository'
    required: true
  parsers-loaded:
    description: 'Parsing Libraries Enabled'
    required: false
    default: 'spack'
  general-action:
    description: 'Tells Binoc if it's running as a GitHub action or not.
    required: false
    default: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/autamus/binoc:latest'
